services:
  - type: web
    name: sigcoins-backend
    env: node
    buildCommand: |
      cd Backend
      npm install
    startCommand: |
      cd Backend
      node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true 