name: Full Project CI/CD Workflow

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from GitHub repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Frontend CI
    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Use Node.js v18 for frontend

    - name: Install dependencies for Frontend
      working-directory: Frontend/vite-project
      run: |
        npm install

    - name: Build the Frontend
      working-directory: Frontend/vite-project
      run: |
        npm run build

    # Backend CI
    - name: Set up Node.js for Backend
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Use Node.js v18 for backend

    - name: Install dependencies for Backend
      working-directory: Backend
      run: |
        npm install

    


